# Jekyll configuration for Open SDG platform

# primary settings:
baseurl: "/goettingen-site" # change here!
# remote_data_prefix: "https://open-sdg.org/open-sdg-data-starter"
remote_data_prefix: https://open-sdg-germany.usercontent.opencode.de/goettingen-data


# URL for the "Edit Data" and "Edit Metadata" button on indicators.
data_edit_url: http://prose.io/#OpenSDGde/goettingen-data/edit/develop/data/indicator_[id].csv
metadata_edit_url: http://prose.io/#OpenSDGde/goettingen-data/edit/develop/meta/[id].md

# Text zu Handlungsfelder
# fields to change: title, leitsatz, hf-goals

email_contacts:
  questions: nachhaltigkeit@ingolstadt.de
  suggestions: nachhaltigkeit@ingolstadt.de
  functional: nachhaltigkeit@ingolstadt.de

#
# other settings are alphabetically ordered:

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

cookie_consent_form:
  enabled: true

country:
  name: Ingolstadt
  adjective: Ingolstadt

create_indicators:
  layout: indicator
create_goals:
  previous_next_links: false
  goals: []
create_pages:
  - filename: ""
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ""
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ""
    folder: /search
    layout: search
    title: search.search

custom_js:
  - /assets/js/custom.js
  - /assets/js/tpwd.js

exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE
  - .editorconfig
  - .gitmodules
  - data-repo/*
  - theme-repo/*
  - gitlab-ci.yml
  - .prettierrc
  - copy_handlungsfelder.sh
  - package-lock.json
  - package.json
  - tailwind.config.js
  - mise.toml
  - node_modules
  - _site
  - tmp
  - temp
  - "*.log"

footer_language_toggle: none

footer_menu:
  - path: https://StadtIngolstadt.github.io/sdg-data/de/zip/all_indicators.zip
    translation_key: Download
  - path: mailto:nachhaltigkeit@ingolstadt.de
    translation_key: menu.contact_us
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
  - path: /guidance
    translation_key: menu.guidance

frontpage_introduction_banner:
  title: my-custom-translations.frontpage-intro-title
  description: my-custom-translations.frontpage-intro-description

frontpage_goals_grid:
  title: my-custom-translations.my-goals-grid-title
  description: my-custom-translations.my-goals-grid-description

frontpage_cards:
  - title: Nachhaltigkeitsbericht - Stadt Ingolstadt 2021
    href: "https://nachhaltigkeitsagenda-ingolstadt.de/wp-content/uploads/2023/01/221208_BNK_final_web.pdf"
    thumbnail_src: /BNK_Titelbild_1_1.jpg
  - title: Magazin - "Ingolstadt Nachhaltig" - Ausgabe 2022
    href: "https://nachhaltigkeitsagenda-ingolstadt.de/wp-content/uploads/2023/01/IN_Magazin_dpa-CC_FINAL_DIGTAL.pdf"
    thumbnail_src: /IN_Magazin_Titelbild_1_1.jpg
  - title: Nachhaltigkeitsfilm - Stadt Ingolstadt
    href: "https://www.youtube.com/watch?v=LnqFFrIGQQQ"
    thumbnail_src: /Logo N-Agenda_1_1.png
  - title: Video Rückblick - Visionen 2045 Ingolstadt
    href: "https://www.youtube.com/watch?v=VDQF-RdU0nc"
    thumbnail_src: /Logo N-Agenda_1_1.png

goal_image_base: https://open-sdg.org/sdg-translations/assets/img/goals
graph_color_set: accessible
header_language_toggle: dropdown

languages:
  - de

menu:
  - path: /
    translation_key: Startseite
  - path: /goals
    translation_key: general.goals
  - path: /reporting-status
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /faq
    translation_key: menu.faq

menu_top:
  - path: /leichte-sprache
    translation_key: menu.plain_german
  - path: /reiter-english
    translation_key: English

metadata_tabs:
  - scope: national
    title: Metadaten
    description: indicator.national_metadata_blurb

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

remote_theme: OpenSDGde/open-sdg@tpwd

title: general.site_title
url: ""
environment: staging

heroimage:
  src: "HEADER_DashKon_ohne Schrift_Neu.png"
  alt: "Hero Image City Goettingen"
